// <auto-generated />
namespace ContractMonthlyClaimSystemsPrototype.Migrations.Claims
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialClaims : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialClaims));
        
        string IMigrationMetadata.Id
        {
            get { return "202511191531266_InitialClaims"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
